---
pid: tmp/pids/thin.pid
socket: tmp/sockets/thin.sock
timeout: 30
wait: 30
log: log/thin.log
rackup: config.ru
max_conns: 1024
require: []
servers: 3

environment: production
max_persistent_conns: 512
daemonize: true
